### ISSUE TITLE
Automatic use password

### ISSUE THREAD

**Issue by SiR-DanieL** [GaryJones/wordpress-plugin-svn-deploy#16]
Hi,
if i want to automatically add the password to the script, should i simply do

```
echo "1c) Remote SVN repo on WordPress.org. No trailing slash."
printf "($default_svnurl): "
read -e input
input="${input%/}" # Strip trailing slash
SVNURL="${input:-$default_svnurl}" # Populate with default if empty
SVNPASS=" PASSWORD HERE "
echo
```

and then edit the commit commands like

```
svn commit --username=$SVNUSER --password=$SVNPASS -m "Preparing for $NEWVERSION1 release"
```

Is this right?

**Comment by afragen** [comment]
You shouldn't add a password to the script. You should create an ssh key.

**Comment by SiR-DanieL** [comment]
and how do i use it with the script?
Can you give me an example please?

**Comment by afragen** [comment]
I can't quite remember how to set that up right now. I'll have to Google or ask on wp.org forum. But I don't have to enter any passwords when using this script.

**Comment by GaryJones** [comment]
Closing as the repo is being archived.
