### ISSUE TITLE
Install instructions are wrong

### ISSUE THREAD

**Issue by strider72** [GaryJones/wordpress-plugin-svn-deploy#18]
The git command in the install instructions downloads the script into a /wordpress-plugin-git-flow-svn-deploy subdirectory rather than into the current directory.  If that's the intended behavior, you should clarify in the instructions.  If it's not the intended behavior...  ;-)

**Comment by GaryJones** [comment]
Did you include the `.` at the end of the clone command? That optional arg says to install in the current directory. Without it, it defaults to installing into a subdirectory with the same name as the repo.

**Comment by strider72** [comment]
I get this: "fatal: destination path '.' already exists and is not an empty directory."

(I'm on Mac OS 10.10, but running the current version of Git.)

**Comment by strider72** [comment]
(but no, I had overlooked the dot at the end... )

**Comment by GaryJones** [comment]
> and is not an empty directory

Actually, that's probably a valid point, since git only clones into empty directories.

**Comment by bibz** [comment]
If you *really* want to have the script in your plugins folder, I think you would be better just copying it (e.g. `wget https://raw.githubusercontent.com/GaryJones/wordpress-plugin-git-flow-svn-deploy/develop/deploy.sh`).
Cloning a repository inside a non-empty folder, and one that can be full of non-related files like this one is not the best sensible way IMHO.

**Comment by GaryJones** [comment]
Closing as the repo is being archived.
