### ISSUE TITLE
Handle presence of assets folder in plugin

### ISSUE THREAD

**Issue by pdewouters** [GaryJones/wordpress-plugin-svn-deploy#31]
If the plugin directory structure contains an `assets` folder for JS and CSS for example, this gets moved to the root of the svn repo.

**Comment by afragen** [comment]
That is because dot org stores screenshots and header images for the plugin in a folder named `assets` in the root directory of the SVN repo. I would suggest a new naming structure for your plugin.

**Comment by deanoakley** [comment]
Maybe it could be an option as I was also confused and had this problem after using this popular plugin template https://github.com/hlashbrooke/WordPress-Plugin-Template
