### ISSUE TITLE
Creates trunk folder inside trunk

### ISSUE THREAD

**Issue by smithjw1** [GaryJones/wordpress-plugin-svn-deploy#34]
When I run a deploy, it creates a trunk folder inside the existing trunk folder and copies the new files into that folder.

How I can I prevent this behavior?

**Comment by afragen** [comment]
What is your local file path to the plugin?

**Comment by afragen** [comment]
I can't replicate this issue and as the script has undergone significant modification I'm going to close this issue. Please re-open if this issue persists.
