### ISSUE TITLE
Adapt for only updating tagged readme.txt file

### ISSUE THREAD

**Issue by afragen** [GaryJones/wordpress-plugin-svn-deploy#38]
When using the wp.org Plugin Directory, the info from the headers in the designated `Stable tag:` header, usually this is the latest tag, is used for designating compatibility with WP versions. 

As such, updating the `readme.txt` file in the `tags/x.x.x` is needed to update the `Tested up to:` header and thereby keep the plugin up to date. Often no new code is needed to run on current versions of WordPress and only updating this `Tested up to:` header is all that’s needed to show compatibility.

I propose adding code (yes I’ve already written code for this 😉) that would enable simply updating the local readme.txt file, committing those changes locally, and then using the `deploy.sh` script. No new tag needs to be created.

Essentially this would create the following workflow for a plugin that doesn’t require any new code for compatibility with a current WP version.

1. Update the `readme.txt` `Tested up to:` header.
2. Commit those changes.
3. Run `deploy.sh`

What should happen is that only the `readme.txt` file should be uploaded to `trunk` and `tags/x.x.x` where `x.x.x` is the current tag. There is no need to tag another release.

Thoughts?

**Comment by GaryJones** [comment]
Sounds useful - go for it :-)
