### ISSUE TITLE
vendor/ folder is being ignored

### ISSUE THREAD

**Issue by rahilwazir** [GaryJones/wordpress-plugin-svn-deploy#40]
I have `vendor/` directory for my plugin. When I use `deploy.sh` the `vendor/` directory is not included in the SVN repository.

**NB:** `vendor/` directory is in `.gitignore` list

**Comment by afragen** [comment]
The `.gitignore` file is supposed to contain files/directories to be ignored and not under version control.

Is there something else you’re intending to accomplish by having the `vendor/` in `.gitignore`?

**Comment by GaryJones** [comment]
I think in this case, @rahilwazir would want to ignore vendor directory for Git (development - developer can run `composer install`), but allow it to be added to SVN (where the _full_ set of plugin files are needed).

**Comment by afragen** [comment]
I think the issue here is since `vendor/` isn’t under version control it isn’t brought into the local SVN directory on https://github.com/GaryJones/wordpress-plugin-svn-deploy/blob/81130156b9ec99de820c766e26ccd927e870d006/deploy.sh#L178

**Comment by rahilwazir** [comment]
https://github.com/GaryJones/wordpress-plugin-svn-deploy/blob/81130156b9ec99de820c766e26ccd927e870d006/deploy.sh#L178

After this, can we manually check if there is `vendor/` directory, it should be copied to the `$SVN/trunk/` via `cp` command? Since the `git checkout-index` only copy files added to the GIT index.

**Comment by afragen** [comment]
I think we need to consider how to accommodate both composer and other build processes. Perhaps we need to add a `.build` file similar to the `.svnignore` but work it opposite where the files/folders listed as added to SVN trunk. 

Thoughts?

**Comment by afragen** [comment]
Perhaps we could simply run `composer update —prefer-dist` from SVN/trunk?

**Comment by rahilwazir** [comment]
The latter. I had the same thought but it looks counter productive to add a new file for add

> Perhaps we could simply run `composer update —prefer-dist` from SVN/trunk?

For that we would need `composer.json` & `composer.lock` and then after the update we delete those composer files, right?

**Comment by afragen** [comment]
Those files could be added to `.svnignore` file and they would be removed.

**Comment by afragen** [comment]
I have to say that I don't use this script any longer. I have switched over to using the GitHub Action written by 10up.

**Comment by caercam** [comment]
Yeah, I figured that later reading #46. Thanks anyway!

**Comment by GaryJones** [comment]
Closing as the repo is being archived.
