### ISSUE TITLE
Linting for bash script?

### ISSUE THREAD

**Issue by afragen** [GaryJones/wordpress-plugin-svn-deploy#42]
I'm currently using VSCode and there's a extension for formatting shell scripts, https://marketplace.visualstudio.com/items?itemName=foxundermoon.shell-format

I can add a PR using this if you want.

**Comment by GaryJones** [comment]
I find just copying it into shellcheck.net, or using a local equivalent inspection for PHPStorm is sufficient. I'm open to a PR to apply the fixes these suggest.
