### ISSUE TITLE
Is this still valid?

### ISSUE THREAD

**Issue by luisrock** [GaryJones/wordpress-plugin-svn-deploy#46]
Considering 17 months with no updates... Is anybody still using it successfully?

**Comment by afragen** [comment]
I still use the develop branch, though I believe most developers are transitioning over to using the GitHub Actions that @10up has developed.

https://github.com/10up/actions-wordpress

**Comment by GaryJones** [comment]
I myself am using the deploy action from 10up, so I'll let you draw your own conclusions :-)

**Comment by afragen** [comment]
For completeness, I too am using 10up's deploy action.
