### ISSUE TITLE
Looks great! Can you provide more instruction?

### ISSUE THREAD

**Issue by MickeyKay** [GaryJones/wordpress-plugin-svn-deploy#9]
Hiya Gary,

This looks fantastic for the type of development flow I'd like to implement, however I don't quite know how to get started. Do I need git-flow installed to use this workflow? I'm not super familiar with bash scripts, so is there a command I run, or a script I need to deploy (perhaps, deploy.sh, right)? Any chance you could add a quick starter guide for newbies like myself?

Thanks man, you rock!

**Comment by GaryJones** [comment]
Closing as the repo is being archived.
